### ISSUE TITLE
Relacionar usuario UO´s

### ISSUE THREAD

**Issue by Estepfany** [popepatas/CU#11]
Se debe adicionar los títulos a la 1er y ultima columna del reporte del formulario
![image](https://cloud.githubusercontent.com/assets/15731914/15758518/96195d8a-28d0-11e6-9842-91b9301b05dc.png)

**Comment by popepatas** [comment]
Se les coloco "NRO" y "SELECCIONAR". Solucionado "creo" yo

**Comment by Estepfany** [comment]
Para cerrar issues
Se verifica la solución indica;
=> Resuelto
