### ISSUE TITLE
Eliminar empresa

### ISSUE THREAD

**Issue by Estepfany** [popepatas/CU#12]
Se crea una empresa y posteriormente se indica su eliminación, se realiza el proceso y el sistema arroja el siguiente error
![image](https://cloud.githubusercontent.com/assets/15731914/15758719/83428302-28d1-11e6-8f1b-94a55346c2bc.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by Estepfany** [comment]
Para cerrar issues
Se verifica la solución indica;
=> Resuelto
