### ISSUE TITLE
Administrar empresas - servicios

### ISSUE THREAD

**Issue by Estepfany** [popepatas/CU#15]
Se intentó adicionar un servicio a la empresa "Alipapa de oscar2" , se ingresó la información sin especificar una imagen y se indicó almacenar el registro, el formulario se quedó en blanco, no se registro el servicio
![image](https://cloud.githubusercontent.com/assets/15731914/15760525/3d259cf8-28d9-11e6-9612-f5d1779e28d3.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by Estepfany** [comment]
Se debe adicionar una mensaje en el cual se indique que el proceso se logro realizar, ya que actualmente no lo tiene, verificar y corregir

**Comment by AndresTello** [comment]
resuelto.

también se agrego el mensaje de confirmación al momento de guardar

**Comment by Estepfany** [comment]
Para cerrar issues
Se verifica la solución indica;
=> Resuelto
