### ISSUE TITLE
opción de envío de mensajes

### ISSUE THREAD

**Issue by Estepfany** [popepatas/CU#16]
Se debe omitir la función de enviar mensaje, esta opción se encuentra en la configuración del aplicativo una vez se indique la opción de configuración con un usuario administrador, la opción está señalada en la siguiente imagen
![image](https://cloud.githubusercontent.com/assets/15731914/15761176/6af2ecf0-28dc-11e6-977e-3492587eb82d.png)

**Comment by popepatas** [comment]
solucionado, se quito el iconito

**Comment by Estepfany** [comment]
Para cerrar issues
Se verifica la solución indica;
=> Resuelto
