### ISSUE TITLE
Consulta de eventos

### ISSUE THREAD

**Issue by Estepfany** [popepatas/CU#18]
Se debe modificar el nombre del formulario cuando se realiza el proceso de consulta con un usuario diferente de administrador, además verificar si del componente en el cual se muestra la imagen se puede omitir el botón de seleccionar
- verificar si es posible ampliar el largo de la ventana emergente del evento

![image](https://cloud.githubusercontent.com/assets/15731914/15780826/1497115a-2969-11e6-881d-4a8df63a34c9.png)

**Comment by popepatas** [comment]
Se cambio el titulo a algo que sirva pa los dos perfiles.
El boton no se puede quitar

**Comment by popepatas** [comment]
listo lo del boton. Lo de la pantalla seria mejora a muy futuro

**Comment by Estepfany** [comment]
Se intenta ver en detalle la imagen y no funciona de la manera correcta, verificar y corregir
![image](https://cloud.githubusercontent.com/assets/15731914/15866248/7c646b92-2ca3-11e6-9fec-dc466330cfea.png)

**Comment by popepatas** [comment]
solucionado

**Comment by Estepfany** [comment]
Para cerrar issues
Se verifica la solución indica;
=> Resuelto
