### ISSUE TITLE
Registrarse

### ISSUE THREAD

**Issue by Estepfany** [popepatas/CU#2]
Se realiza el 1er paso para realizar el proceso de registrarse, se ingresa la información solicitada en el formulario, y se informa que se debe continuar con el proceso una vez se cuente con el mensaje enviado al correo electrónico, pero este no llega, además se realiza la consulta con el usuario "jmarmolejo" con el fin de verificar si el usuario fué o no creado, se evidencia que se creó el usuario sin validar si el nombre de usuario (login) esta o no en mayúscula
![image](https://cloud.githubusercontent.com/assets/15731914/15751264/1a38430a-28af-11e6-9b48-33a36ab7ebbf.png)
NOTA: El usuario no debería estar Activo si aún no a terminado el proceso de registro, corregir

**Comment by popepatas** [comment]
corregido.

**Comment by Estepfany** [comment]
Para cerrar issues
Se verifica la solución indica;
=> Resuelto
