### ISSUE TITLE
información corporativa - noticias

### ISSUE THREAD

**Issue by Estepfany** [popepatas/CU#23]
Se requiere editar una noticia y se evidencia que no se carga la imagen asociada, se debe adicionar la imagen
![image](https://cloud.githubusercontent.com/assets/15731914/15783266/17d879bc-2973-11e6-8807-df7dd474fbf7.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by Estepfany** [comment]
Para cerrar issues
Se verifica la solución indica;
=> Resuelto
