### ISSUE TITLE
información corporativa - noticias

### ISSUE THREAD

**Issue by Estepfany** [popepatas/CU#24]
Se intenta adicionar un comentario a la noticia consultada pero el comentario no se ve hasta que se indica publicar
![image](https://cloud.githubusercontent.com/assets/15731914/15783523/19bba69a-2974-11e6-8e04-bc4399e5f357.png)

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by Estepfany** [comment]
Se revisa, resuelto
