### ISSUE TITLE
Eventos

### ISSUE THREAD

**Issue by Estepfany** [popepatas/CU#25]
Se crea un evento y se evidencia que a la hora de consultar en la página de la comuna uno no se muestra la hora especificada en la creación, se intenta realizar la modificación del evento y se evidencia que no toma la hora exacta, verificar y corregir
![image](https://cloud.githubusercontent.com/assets/15731914/15784275/67f4b18c-2977-11e6-8bd7-2d4dd81f25cd.png)

**Comment by popepatas** [comment]
corregido y verificado

**Comment by Estepfany** [comment]
Para cerrar issues
Se verifica la solución indica;
=> Resuelto
