### ISSUE TITLE
Eventos

### ISSUE THREAD

**Issue by Estepfany** [popepatas/CU#26]
Se realiza la inactivación de un evento y se evidencia que el evento se sigue visualizando en la página de comunidad uno sin importar que se encuentre en estado igual a inactivo
![image](https://cloud.githubusercontent.com/assets/15731914/15784628/efaf180a-2978-11e6-974f-847fa0ed6e40.png)

**Comment by popepatas** [comment]
corregido, solo muestra los activos

**Comment by Estepfany** [comment]
Para cerrar issues
Se verifica la solución indica;
=> Resuelto
