### ISSUE TITLE
Fotos

### ISSUE THREAD

**Issue by Estepfany** [popepatas/CU#27]
Se intenta crear un álbum y se evidencia que en el campo en el cual se indica el nombre de usuario no se visualiza lo que se ingresa
![image](https://cloud.githubusercontent.com/assets/15731914/15784992/b062f660-297a-11e6-907d-ba2a555bf2c9.png)

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by Estepfany** [comment]
Se revisa, resuelto
