### ISSUE TITLE
videos

### ISSUE THREAD

**Issue by Estepfany** [popepatas/CU#28]
Se ingresa la url en el campo "URL del video en Youtube" se evidencia que la url no se ve a menos de que sea seleccionada
![image](https://cloud.githubusercontent.com/assets/15731914/15785546/66290e1a-297d-11e6-8685-b48979475431.png)

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by Estepfany** [comment]
Se revisa, resuelto
