### ISSUE TITLE
videos

### ISSUE THREAD

**Issue by Estepfany** [popepatas/CU#29]
Una vez seleccionado el video y especificado la UO´s si se cierra el combo no se visualiza las UO´s seleccionadas, solo se muestran de manera rápida si se indica "iniciar carga"
NOTA: Como se puede identificar las UO´s con las cuales se compartió el video?!
![image](https://cloud.githubusercontent.com/assets/15731914/15786010/ea303402-297f-11e6-905d-da6c7b9f8571.png)

**Comment by popepatas** [comment]
estilo fantasma, pasando a christiaan la pelota.

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by Estepfany** [comment]
Revisado, resuelto
