### ISSUE TITLE
Videos

### ISSUE THREAD

**Issue by Estepfany** [popepatas/CU#30]
Una vez se carga el video y se selecciona del listado de videos se visualiza la opción de borrar,  se recomienda mover el icono de borrar y lo mismo seria para el icono de eliminar en el listado de videos
![image](https://cloud.githubusercontent.com/assets/15731914/15786108/74009604-2980-11e6-9b61-cf815cb8bc2e.png)

**Comment by AndresTello** [comment]
se asigna al area de diseño

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by Estepfany** [comment]
Se revisa, resuelto
