### ISSUE TITLE
Palabra clave

### ISSUE THREAD

**Issue by Estepfany** [popepatas/CU#33]
En todos los formulario en los cuales se encuentra este campo no se logra visualizar la información que se digita, verificar y corregir
![image](https://cloud.githubusercontent.com/assets/15731914/15789014/d4752ee6-298f-11e6-9325-1a896b193f1b.png)

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by Estepfany** [comment]
revisado, resuelto
