### ISSUE TITLE
Regístrate

### ISSUE THREAD

**Issue by Estepfany** [popepatas/CU#35]
Se debe modificar la apariencia del formulario ya que actualmente se esta manejando lo utilizado en el aplicativo de geco, además el cambio de los términos y condiciones ya que en ellos se indica a geco como el aplicativo
![image](https://cloud.githubusercontent.com/assets/15731914/15789694/32d7fd58-2993-11e6-8dd7-0b1f55f7dc81.png)

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by Estepfany** [comment]
Se revisa y se evidencia que la opción para obtener los términos y condiciones no esta funcionando, ademas aun se indica GECO en la pestaña, corregir 
![image](https://cloud.githubusercontent.com/assets/15731914/16734386/fc8046d6-474a-11e6-982f-4d326a19d4fc.png)
