### ISSUE TITLE
Notificación de amistad

### ISSUE THREAD

**Issue by Estepfany** [popepatas/CU#36]
Se crea un nuevo usuario A y este envía una solicitud de amistad al usuario B, el usuario B verifica y acepta la solicitud de amistad y en el recuadro de solicitudes aparece el número 10 pero a su vez indica que no tiene más notificaciones, verificar y corregir
NOTA: revisar si el mensaje que se visualiza una vez se selecciona el recuadro de notificaciones de amistad se puede colocar en español
![image](https://cloud.githubusercontent.com/assets/15731914/15790543/74dad190-2997-11e6-820c-b868397290a5.png)

**Comment by popepatas** [comment]
solucionado

**Comment by Estepfany** [comment]
Para cerrar issues
Se verifica la solución indica;
=> Resuelto
