### ISSUE TITLE
Reporte de notificaciones

### ISSUE THREAD

**Issue by Estepfany** [popepatas/CU#37]
Se indica visualizar las notificaciones del usuario para lo cual se despliega el reporte de notificaciones, se debe adicionar el titulo a la última columna del reporte
![image](https://cloud.githubusercontent.com/assets/15731914/15790630/f60b562c-2997-11e6-8fae-221e3caca858.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by Estepfany** [comment]
Para cerrar issues
Se verifica la solución indica;
=> Resuelto
