### ISSUE TITLE
Información del servicio de la empresa

### ISSUE THREAD

**Issue by Estepfany** [popepatas/CU#38]
Se debe verificar si se puede adicionar el horario de atención al servicio o a la empresa
![image](https://cloud.githubusercontent.com/assets/15731914/15792165/24e5e350-29a1-11e6-8da4-a47ddc889c34.png)

**Comment by AndresTello** [comment]
se decide con sergio que no se va a hacer

**Comment by Estepfany** [comment]
Se cierra por la decisión informada.
