### ISSUE TITLE
articulos

### ISSUE THREAD

**Issue by Estepfany** [popepatas/CU#39]
Se intenta especificar el titulo del articulo y este no se hace visible hasta que se indica la acción de guardar, ademas el campo palabra clave se comporta igual
![image](https://cloud.githubusercontent.com/assets/15731914/15792322/28d21b54-29a2-11e6-94b0-e54c7054ec0f.png)

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by Estepfany** [comment]
revisado, resuelto
