### ISSUE TITLE
UO´s

### ISSUE THREAD

**Issue by Estepfany** [popepatas/CU#4]
Consulta:
Se debe verificar y corregir la consulta por los diferentes filtros ya que no esta funcionando correctamente, no toma en cuenta los filtros especificados
![image](https://cloud.githubusercontent.com/assets/15731914/15752816/6615ae10-28b5-11e6-89fa-a45e3f889cbd.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by Estepfany** [comment]
Para cerrar issues
Se verifica la solución indica;
=> Resuelto
