### ISSUE TITLE
Enviar solicitud de unirse a un grupo

### ISSUE THREAD

**Issue by Estepfany** [popepatas/CU#40]
Una vez llega el mensaje al usuario para unirse a un grupo y es llevado al grupo solo se cuenta con la opción de "unirme al grupo", se da clic en esta opción pero al usuario no se le retorna un mensaje indicando que si el proceso se realizó o no, adicionar mensaje emergente
![image](https://cloud.githubusercontent.com/assets/15731914/15793357/f620f07a-29a8-11e6-9bb8-92b69c638e1d.png)

**Comment by popepatas** [comment]
Colocar alertify diciendo "Se ha enviado su solicitud al administrador del grupo, el cual evaluará si lo acepta o no como parte del grupo"

**Comment by AndresTello** [comment]
resuelto

**Comment by Estepfany** [comment]
Para cerrar issues
Se verifica la solución indica;
=> Resuelto
