### ISSUE TITLE
Grupo - mensaje masivo

### ISSUE THREAD

**Issue by Estepfany** [popepatas/CU#41]
Verificar si se puede omitir la palabra masivo de la opción mensaje masivo, ya que esta opción permite realizar el envio de ambas formas, tanto masivo como individual
![image](https://cloud.githubusercontent.com/assets/15731914/15793780/f08f8876-29ab-11e6-98db-834040839bce.png)

**Comment by popepatas** [comment]
se cambia el label "Mensajes Masivos" por "Mensajes"

**Comment by Estepfany** [comment]
Para cerrar issues
Se verifica la solución indica;
=> Resuelto
