### ISSUE TITLE
Fotos grupo

### ISSUE THREAD

**Issue by Estepfany** [popepatas/CU#42]
Se intenta especificar el nombre del álbum y este no se hace visible hasta que se indica la acción de cargar las imagenes
![image](https://cloud.githubusercontent.com/assets/15731914/15858444/258c4d5c-2c86-11e6-92ce-095f03e73873.png)

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by Estepfany** [comment]
revisado, resuelto
