### ISSUE TITLE
Videos grupo

### ISSUE THREAD

**Issue by Estepfany** [popepatas/CU#43]
Se ingresa la url en el campo "URL del video en Youtube" se evidencia que la url no se ve a menos de que sea seleccionada
![image](https://cloud.githubusercontent.com/assets/15731914/15858655/360cb5e4-2c87-11e6-83d7-0b4c6ffc06d2.png)

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by Estepfany** [comment]
revisado, resuelto
