### ISSUE TITLE
Directorio

### ISSUE THREAD

**Issue by Estepfany** [popepatas/CU#44]
Se realiza la consulta de una empresa, especificando el nombre de la empresa, se indica la opción "Realizar búsqueda", se evidencia que una vez se cuente con el resultado no se retrae la sección de búsqueda, y que la sección en la cual se encuentra el resultado de la búsqueda puede pasar por encima de los campos de búsqueda pero por debajo del icono de menú utilizado para expandir la sección de búsqueda; se solicita que una vez se cuente con el resultado de la búsqueda la sección de búsqueda se retraiga además se recomienda modificar la imagen del icono
Una vez terminada la busqueda los campos de los filtros deben quedar limpios
![image](https://cloud.githubusercontent.com/assets/15731914/15860089/4d07ff3c-2c8d-11e6-8c21-e22c007ca2ef.png)

**Comment by AndresTello** [comment]
resuelto.

se asigna al area de diseño el cambio del icono que abre la sección de filtros de busqueda.

**Comment by ChristiaanGuzman** [comment]
el cambio de icono no es necesario realizarlo ya que las 3 barras indican que es un icono de menu y no hay necesidad de mostrar que este icono se abre o cierra  envio ejmplos

http://codepen.io/Gugor/pen/xbGMPy

![como-hacer-un-menu-de-navegacion-adaptable-a-dispositivos-moviles-responsive-design](https://cloud.githubusercontent.com/assets/15741537/15864257/fc72098c-2c9b-11e6-98c0-6f856d11ec38.jpg)

**Comment by Estepfany** [comment]
falta que los campos queden limpios una vez se ejecute la consulta

**Comment by AndresTello** [comment]
resuelto

**Comment by Estepfany** [comment]
Para cerrar issues
Se verifica la solución indica;
=> Resuelto
