### ISSUE TITLE
Mensaje de notificación

### ISSUE THREAD

**Issue by Estepfany** [popepatas/CU#45]
Se debe modificar el mensaje de notificación de amistad, debería quedar de la siguiente manera: "El usuario (nombre y apellido del usuario) ha aceptado su solicitud de amistad"
![image](https://cloud.githubusercontent.com/assets/15731914/15864037/0539a760-2c9b-11e6-9755-80d77c47a354.png)

**Comment by popepatas** [comment]
corregido

**Comment by Estepfany** [comment]
Para cerrar issues
Se verifica la solución indica;
=> Resuelto

**Comment by Estepfany** [comment]
Para cerrar issues
Se verifica la solución indica;
=> Resuelto
