### ISSUE TITLE
Cambio de unidad organizacional

### ISSUE THREAD

**Issue by Estepfany** [popepatas/CU#46]
Se realiza el cambio de UO a un usuario y como resultado del proceso se debe enviar un correo informando al usuario que ha sido modificado de UO, este correo debe cambiar ya que contiene información de GECO, se debe adicionar el logo de comuna uno, en el mensaje de se modificar la parte en la cual se indica "administrador de GECO" por "administrador de Comuna uno"
![image](https://cloud.githubusercontent.com/assets/15731914/15865249/b102cc44-2c9f-11e6-936c-56b574c6a062.png)

**Comment by AndresTello** [comment]
resuelto.

El cambio de logo se asigna al area de diseño

**Comment by ChristiaanGuzman** [comment]
resuelto

**Comment by Estepfany** [comment]
se revisa, resuelto
