### ISSUE TITLE
Evento

### ISSUE THREAD

**Issue by Estepfany** [popepatas/CU#48]
Se intenta modificar la hora de un evento indicando la hora final menor a la hora inicial y se realiza la validación correspondiente pero el mensaje que se visualiza no es correcto, corregir "Hora inical" por "Hora inicial" ademas de omitir la coma (,)
![image](https://cloud.githubusercontent.com/assets/15731914/15869385/d36b25d0-2cb1-11e6-990c-d7ae0af58210.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by Estepfany** [comment]
Para cerrar issues
Se verifica la solución indica;
=> Resuelto
