### ISSUE TITLE
Iniciar sesión 

### ISSUE THREAD

**Issue by Estepfany** [popepatas/CU#49]
Se debe omitir la opción de iniciar sesión desde los dispositivos móviles
![image](https://cloud.githubusercontent.com/assets/15731914/15874324/3bf2c3cc-2cc8-11e6-9fbf-d9d63dbec05d.png)

**Comment by popepatas** [comment]
solucionado

**Comment by Estepfany** [comment]
Para cerrar issues
Se verifica la solución indica;
=> Resuelto
