### ISSUE TITLE
UO´s

### ISSUE THREAD

**Issue by Estepfany** [popepatas/CU#5]
Eliminar:
Se realiza el proceso para crear una UO, se crea y luego se elimina, se debe tener en cuenta que no se adiciono ningún usuario a la UO, el sistema informa que la eliminación se realizó, de nuevo se intenta crear una UO con el mismo nombre de la ya eliminada UO y no lo permite, se debe verificar si la eliminación se está realizando en realidad o las condiciones de creación de UO están en conflicto, ya que en este caso debería crear la UO
![image](https://cloud.githubusercontent.com/assets/15731914/15752853/988a03dc-28b5-11e6-9780-6cd596185b23.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by Estepfany** [comment]
Para cerrar issues
Se verifica la solución indica;
=> Resuelto
