### ISSUE TITLE
perfil

### ISSUE THREAD

**Issue by Estepfany** [popepatas/CU#50]
Una vez se realiza el proceso de logueo, se indica la opción de amigos, se selecciona uno de ellos y el sistema redirecciona al usuario al perfil del amigo indicado, en la parte superior derecha se cuenta con una opción "Nombre del usuario" que debería enviar al usuario a su perfil pero solo realiza un recargue de la pagina actual, se debe modificar, al indicar esta opción debe direccionar al usuario a su propio perfil
![image](https://cloud.githubusercontent.com/assets/15731914/15896564/747967bc-2d56-11e6-8ecc-7b5c4ed1bc2c.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by Estepfany** [comment]
Para cerrar issues
Se verifica la solución indica;
=> Resuelto
