### ISSUE TITLE
Modos de comunicación

### ISSUE THREAD

**Issue by Estepfany** [popepatas/CU#6]
Se debe verificar la consulta de los modos de comunicación ya que se especifica parte del modo de comunicación y se logra obtener el resultado, ejemplo, se especifica en el nombre la palabra amistad y se indica la opción consultar pero el sistema no arroja ningún resultado
![image](https://cloud.githubusercontent.com/assets/15731914/15753169/4a0b8918-28b7-11e6-86db-6821c4467a3e.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by Estepfany** [comment]
Para cerrar issues
Se verifica la solución indica;
=> Resuelto
