### ISSUE TITLE
Relación entre OU´s

### ISSUE THREAD

**Issue by Estepfany** [popepatas/CU#7]
Se evidencia que no se está validando que la selección de la UO destino sea diferente de la UO origen, verificar y corregir
![image](https://cloud.githubusercontent.com/assets/15731914/15757318/aea82ca6-28ca-11e6-9ed2-7cbedcf0c2b4.png)

**Comment by AndresTello** [comment]
resuelto

**Comment by Estepfany** [comment]
Para cerrar issues
Se verifica la solución indica;
=> Resuelto
