### ISSUE TITLE
Opción de cargue masivo de usuarios

### ISSUE THREAD

**Issue by Estepfany** [popepatas/CU#8]
Se intenta acceder a esta opción y se evidencia que se está direccionando al formulario de "Regístrate", verificar si esta opción debe ir y de ser así hacer el llamado al formulario correspondiente, si no debe ir, se debe quitar la opción del menú
![image](https://cloud.githubusercontent.com/assets/15731914/15757431/261a0110-28cb-11e6-9bb6-e62a3ae95752.png)

**Comment by popepatas** [comment]
Esto fue por una caida del servicio de la pagina. 
Solucionado

**Comment by Estepfany** [comment]
Para cerrar issues
Se verifica la solución indica;
=> Resuelto
