### ISSUE TITLE
Relacionar usuario UO´s

### ISSUE THREAD

**Issue by Estepfany** [popepatas/CU#9]
Se intenta acceder a esta opción y se evidencia que se está direccionando al formulario de "Regístrate", verificar si esta opción debe ir y de ser así hacer el llamado al formulario correspondiente, si no debe ir, se debe quitar la opción del menú
![image](https://cloud.githubusercontent.com/assets/15731914/15757513/7db60bd0-28cb-11e6-8769-b54d15981839.png)

**Comment by AndresTello** [comment]
se estaba reiniciando la app en el servidor

**Comment by Estepfany** [comment]
Para cerrar issues
Se verifica la solución indica;
=> Resuelto
